### ISSUE TITLE
App crashing on Text Recognition, Image Detection

### ISSUE THREAD

**Issue by shivamkumard107** [shivamkumard107/FirebaseMLKit#5]
Find out the reason and give a PR by fixing the error of crash.

**Comment by osirvics** [comment]
I would love to give this a shot, but I can't reproduce the bug. Text Recognition and Image detection are not throwing an exception. Can you throw more light on this?

**Comment by shivamkumard107** [comment]
The bug is fixed now, and the app is working just fine. Are you interested in implementing the features 
Object Detection n Tracking, Landmark detection, OnDevice Translation? Please help me in this
